"""Configuration constants and code maps for the STATS19 Intelligence Platform."""

from pathlib import Path
from typing import Dict

DATASET_CANDIDATES = [
    Path("dataset"),
    Path("datasets"),
]

CODE_MAPS: Dict[str, Dict[int, str]] = {
    "collision_severity": {1: "Fatal", 2: "Serious", 3: "Slight"},
    "day_of_week": {
        1: "Sunday",
        2: "Monday",
        3: "Tuesday",
        4: "Wednesday",
        5: "Thursday",
        6: "Friday",
        7: "Saturday",
    },
    "urban_or_rural_area": {
        1: "Urban",
        2: "Rural",
        3: "Unallocated",
        -1: "Data missing or out of range",
    },
    "light_conditions": {
        1: "Daylight",
        4: "Darkness - lights lit",
        5: "Darkness - lights unlit",
        6: "Darkness - no lighting",
        7: "Darkness - lighting unknown",
        -1: "Data missing or out of range",
    },
    "weather_conditions": {
        1: "Fine no high winds",
        2: "Raining no high winds",
        3: "Snowing no high winds",
        4: "Fine + high winds",
        5: "Raining + high winds",
        6: "Snowing + high winds",
        7: "Fog or mist",
        8: "Other",
        9: "Unknown",
        -1: "Data missing or out of range",
    },
    "road_surface_conditions": {
        1: "Dry",
        2: "Wet or damp",
        3: "Snow",
        4: "Frost or ice",
        5: "Flood over 3cm. deep",
        6: "Oil or diesel",
        7: "Mud",
        9: "Unknown",
        -1: "Data missing or out of range",
    },
    "road_type": {
        1: "Roundabout",
        2: "One way street",
        3: "Dual carriageway",
        6: "Single carriageway",
        7: "Slip road",
        9: "Unknown",
        12: "One way street/Slip road",
        -1: "Data missing or out of range",
    },
    "vehicle_manoeuvre": {
        -1: "Data missing or out of range",
        1: "Reversing",
        2: "Parked",
        3: "Waiting to go ahead",
        4: "Slowing or stopping",
        5: "Moving off",
        6: "U-turn",
        7: "Turning left",
        8: "Waiting to turn left",
        9: "Turning right",
        10: "Waiting to turn right",
        11: "Changing lane to left",
        12: "Changing lane to right",
        13: "Over taking moving vehicle on its offside",
        14: "Overtaking stationary vehicle on its offside",
        15: "Overtaking on nearside (passengers side nearest kerb)",
        19: "Going ahead",
        20: "Parking",
        99: "Unknown",
    },
    "first_point_of_impact": {
        -1: "Data missing or out of range",
        0: "Did not impact",
        1: "Front",
        2: "Back",
        3: "Offside",
        4: "Nearside",
        9: "Unknown",
    },
    "skidding_and_overturning": {
        -1: "Data missing or out of range",
        0: "No skidding/overturning",
        1: "Skidded",
        2: "Skidded and overturned",
        3: "Jackknifed",
        4: "Jackknifed and overturned",
        5: "Overturned",
        9: "Unknown",
    },
    "hit_object_in_carriageway": {
        -1: "Data missing or out of range",
        0: "No in-carriageway object hit",
        1: "Previous accident",
        2: "Road works",
        4: "Parked vehicle",
        5: "Bridge (roof)",
        6: "Bridge (side)",
        7: "Bollard or refuge",
        8: "Open door of vehicle",
        9: "Central island of roundabout",
        10: "Kerb",
        11: "Other object",
        12: "Any animal (except ridden horse)",
        99: "Unknown",
    },
    "vehicle_leaving_carriageway": {
        -1: "Data missing or out of range",
        0: "Did not leave carriageway",
        1: "Nearside",
        2: "Nearside and rebounded",
        3: "Straight ahead at junction",
        4: "Offside on to central reservation",
        5: "Offside on to centrl res + rebounded",
        6: "Offside - crossed central reservation",
        7: "Offside",
        8: "Offside and rebounded",
        9: "Unknown",
    },
    "hit_object_off_carriageway": {
        -1: "Data missing or out of range",
        0: "No off-carriageway object hit",
        1: "Road sign or traffic signal",
        2: "Lamp post",
        3: "Telegraph or electricity pole",
        4: "Tree",
        5: "Bus stop or bus shelter",
        6: "Central crash barrier",
        7: "Near/Offside crash barrier",
        8: "Submerged in water",
        9: "Entered ditch",
        10: "Other permanent object",
        11: "Wall or fence",
        99: "Unknown",
    },
    "journey_purpose_of_driver": {
        -1: "Data missing or out of range",
        1: "Journey as part of work",
        2: "Commuting to or from work",
        6: "Not known or not requested",
        7: "Education and educational escort",
        8: "Emergency vehicle (blue light) on response",
        9: "Personal business or leisure",
    },
    "sex_of_casualty": {
        1: "Male",
        2: "Female",
        9: "Unknown",
        -1: "Data missing or out of range",
    },
    "age_band_of_casualty": {
        1: "0-5",
        2: "6-10",
        3: "11-15",
        4: "16-20",
        5: "21-25",
        6: "26-35",
        7: "36-45",
        8: "46-55",
        9: "56-65",
        10: "66-75",
        11: "Over 75",
        -1: "Missing",
    },
    "age_band_of_driver": {
        1: "0-5",
        2: "6-10",
        3: "11-15",
        4: "16-20",
        5: "21-25",
        6: "26-35",
        7: "36-45",
        8: "46-55",
        9: "56-65",
        10: "66-75",
        11: "Over 75",
        -1: "Missing",
    },
    "casualty_class": {
        1: "Driver or rider",
        2: "Passenger",
        3: "Pedestrian",
    },
    "casualty_severity": {
        1: "Fatal",
        2: "Serious",
        3: "Slight",
    },
    "casualty_type": {
        0: "Pedestrian",
        1: "Cyclist",
        2: "Motorcycle 50cc and under rider or passenger",
        3: "Motorcycle 125cc and under rider or passenger",
        4: "Motorcycle over 125cc and up to 500cc rider or passenger",
        5: "Motorcycle over 500cc rider or passenger",
        8: "Taxi/Private hire car occupant",
        9: "Car occupant",
        10: "Minibus occupant",
        11: "Bus/coach occupant",
        16: "Horse rider",
        17: "Agricultural vehicle occupant",
        18: "Tram occupant",
        19: "Van/Goods vehicle occupant",
        20: "Goods vehicle 3.5t-7.5t occupant",
        21: "Goods vehicle 7.5t+ occupant",
        22: "Mobility scooter rider",
        23: "Electric motorcycle rider or passenger",
        90: "Other vehicle occupant",
        97: "Motorcycle unknown cc rider or passenger",
        98: "Goods vehicle unknown weight occupant",
        99: "Unknown vehicle type (self rep only)",
        -1: "Data missing or out of range",
    },
    "pedestrian_location": {
        0: "Not a Pedestrian",
        1: "Crossing on pedestrian crossing facility",
        2: "Crossing in zig-zag approach lines",
        3: "Crossing in zig-zag exit lines",
        4: "Crossing elsewhere within 50m of crossing",
        5: "In carriageway, crossing elsewhere",
        6: "On footway or verge",
        7: "On refuge/island/central reservation",
        8: "In centre of carriageway",
        9: "In carriageway, not crossing",
        10: "Unknown or other",
        -1: "Data missing or out of range",
    },
    "pedestrian_movement": {
        0: "Not a Pedestrian",
        1: "Crossing from driver's nearside",
        2: "Crossing from nearside, masked",
        3: "Crossing from driver's offside",
        4: "Crossing from offside, masked",
        5: "In carriageway stationary not crossing",
        6: "In carriageway stationary not crossing, masked",
        7: "Walking in carriageway facing traffic",
        8: "Walking in carriageway back to traffic",
        9: "Unknown or other",
        -1: "Data missing or out of range",
    },
    "casualty_imd_decile": {
        1: "Most deprived 10%",
        2: "More deprived 10-20%",
        3: "More deprived 20-30%",
        4: "More deprived 30-40%",
        5: "More deprived 40-50%",
        6: "Less deprived 40-50%",
        7: "Less deprived 30-40%",
        8: "Less deprived 20-30%",
        9: "Less deprived 10-20%",
        10: "Least deprived 10%",
        -1: "Data missing or out of range",
    },
    "casualty_distance_banding": {
        1: "Within 5km of home postcode",
        2: "5.001 to 10km of home postcode",
        3: "10.001 to 20km of home postcode",
        4: "20.001 to 100km of home postcode",
        5: "Over 100km of home postcode",
        -1: "Data missing or out of range",
    },
    "vehicle_type": {
        1: "Pedal cycle",
        2: "Motorcycle 50cc and under",
        3: "Motorcycle 125cc and under",
        4: "Motorcycle over 125cc and up to 500cc",
        5: "Motorcycle over 500cc",
        8: "Taxi/Private hire car",
        9: "Car",
        10: "Minibus",
        11: "Bus/coach",
        17: "Agricultural vehicle",
        19: "Van/Goods under 3.5t",
        20: "Goods 3.5t to 7.5t",
        21: "Goods over 7.5t",
        22: "Mobility scooter",
        23: "Electric motorcycle",
        90: "Other vehicle",
    },
}

LAD_LOOKUP: Dict[str, str] = {
    "E06000001": "Hartlepool",
    "E06000002": "Middlesbrough",
    "E06000003": "Redcar and Cleveland",
    "E06000004": "Stockton-on-Tees",
    "E06000005": "Darlington",
    "E06000006": "Halton",
    "E06000007": "Warrington",
    "E06000008": "Blackburn with Darwen",
    "E06000009": "Blackpool",
    "E06000010": "Kingston upon Hull",
    "E06000011": "East Riding of Yorkshire",
    "E06000012": "North East Lincolnshire",
    "E06000013": "North Lincolnshire",
    "E06000014": "York",
    "E06000015": "Derby",
    "E06000016": "Leicester",
    "E06000017": "Rutland",
    "E06000018": "Nottingham",
    "E06000019": "Herefordshire",
    "E06000020": "Telford and Wrekin",
    "E06000021": "Stoke-on-Trent",
    "E06000022": "Bath and North East Somerset",
    "E06000023": "Bristol",
    "E06000024": "North Somerset",
    "E06000025": "South Gloucestershire",
    "E06000026": "Plymouth",
    "E06000027": "Torbay",
    "E06000030": "Swindon",
    "E06000031": "Peterborough",
    "E06000032": "Luton",
}

LEGACY_LAD_CROSSWALK: Dict[str, Dict[str, str]] = {
    "E07000026": {"district_name": "Allerdale", "current_authority": "Cumberland"},
    "E07000027": {"district_name": "Barrow-in-Furness", "current_authority": "Westmorland and Furness"},
    "E07000028": {"district_name": "Carlisle", "current_authority": "Cumberland"},
    "E07000029": {"district_name": "Copeland", "current_authority": "Cumberland"},
    "E07000030": {"district_name": "Eden", "current_authority": "Westmorland and Furness"},
    "E07000031": {"district_name": "South Lakeland", "current_authority": "Westmorland and Furness"},
    "E07000150": {"district_name": "Corby", "current_authority": "North Northamptonshire"},
    "E07000151": {"district_name": "Daventry", "current_authority": "West Northamptonshire"},
    "E07000152": {"district_name": "East Northamptonshire", "current_authority": "North Northamptonshire"},
    "E07000153": {"district_name": "Kettering", "current_authority": "North Northamptonshire"},
    "E07000154": {"district_name": "Northampton", "current_authority": "West Northamptonshire"},
    "E07000155": {"district_name": "South Northamptonshire", "current_authority": "West Northamptonshire"},
    "E07000156": {"district_name": "Wellingborough", "current_authority": "North Northamptonshire"},
    "E07000163": {"district_name": "Craven", "current_authority": "North Yorkshire"},
    "E07000164": {"district_name": "Hambleton", "current_authority": "North Yorkshire"},
    "E07000165": {"district_name": "Harrogate", "current_authority": "North Yorkshire"},
    "E07000166": {"district_name": "Richmondshire", "current_authority": "North Yorkshire"},
    "E07000167": {"district_name": "Ryedale", "current_authority": "North Yorkshire"},
    "E07000168": {"district_name": "Scarborough", "current_authority": "North Yorkshire"},
    "E07000169": {"district_name": "Selby", "current_authority": "North Yorkshire"},
    "E07000187": {"district_name": "Mendip", "current_authority": "Somerset"},
    "E07000188": {"district_name": "Sedgemoor", "current_authority": "Somerset"},
    "E07000189": {"district_name": "South Somerset", "current_authority": "Somerset"},
    "E07000246": {"district_name": "Somerset West and Taunton", "current_authority": "Somerset"},
    "E08000016": {"district_name": "Barnsley", "current_authority": "Barnsley"},
    "E08000019": {"district_name": "Sheffield", "current_authority": "Sheffield"},
    "EHEATHROW": {"district_name": "Heathrow Airport", "current_authority": "Custom/Transport Code"},
}
